### ISSUE TITLE
Add support for HTTP redirect in IP filtering feature

### ISSUE THREAD

**Issue by jakubkuc** [saleor/requests-hardened#12]
Passing `allow_redirects` flag to requests should be handled in `requests-hardened`.
At the moment it is not possible and additional code is needed to be able to use redirects while using `requests-hardened` and that is not optimal for Saleor.

**Comment by NyanKiyoshi** [comment]
I removed the `bug` label as it IP filtering feature works as intended, it's a feature request.

But the following could be improved:
1. Documentation should warn about the limitation
2. The configuration should reject mixing `ip_filter_enable=True` and `never_redirect=False` as this is unsupported
